name: Build RP2040 Zero Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.32.3

      - name: Download EarlePhilhower RP2040 global package
        run: |
          wget https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          mkdir -p ~/.arduino15/packages/earlephilhower/hardware/rp2040/global
          mv package_rp2040 ~/.arduino15/packages/earlephilhower/hardware/rp2040/global/

      - name: Install EarlePhilhower Pico RP2040 core
        run: |
          arduino-cli core update-index
          arduino-cli core install earlephilhower:rp2040

      - name: Build allhardwaretest.ino
        run: |
          arduino-cli compile --fqbn earlephilhower:rp2040:waveshare_rp2040_zero --output-dir="hardware tests/ino/build" "hardware tests/ino/allhardwaretest"

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: rp2040zero-firmware
          path: "hardware tests/ino/build/*.uf2"
